
CITIES = (
    (1,' An Giang'),
    (2,' Bà Rịa Vũng Tàu'),
    (3,' Bạc Liêu'),
    (4,' Bắc Kạn'),
    (5,' Bắc Giang'),
    (6,' Bắc Ninh'),
    (7,' Bến Tre'),
    (8,' Bình Dương'),
    (9,' Bình Định'),
    (10,' Bình Phước'),
    (11,' Bình Thuận'),
    (12,' Cà Mau'),
    (13,' Cao Bằng'),
    (14,' Cần Thơ – Hậu Giang'),
    (15,' TP. Đà Nẵng'),
    (16,' ĐắkLắk – Đắc Nông'),
    (17,' Đồng Nai'),
    (18,' Đồng Tháp'),
    (19,' Gia Lai'),
    (20,' Hà Giang'),
    (21,' Hà Nam'),
    (22,' TP. Hà Nội'),
    (24,' Hà Tĩnh'),
    (25,' Hải Dương'),
    (26,' TP. Hải Phòng'),
    (27,' Hoà Bình'),
    (28,' Hưng Yên'),
    (29,' TP. Hồ Chí Minh'),
    (30,' Khánh Hoà'),
    (31,' Kiên Giang'),
    (32,' Kon Tum'),
    (33,' Lai Châu – Điện Biên'),
    (34,' Lạng Sơn'),
    (35,' Lao Cai'),
    (36,' Lâm Đồng'),
    (37,' Long An'),
    (38,' Nam Định'),
    (39,' Nghệ An'),
    (40,' Ninh Bình'),
    (41,' Ninh Thuận'),
    (42,' Phú Thọ'),
    (43,' Phú Yên'),
    (44,' Quảng Bình'),
    (45,' Quảng Nam'),
    (46,' Quảng Ngãi'),
    (47,' Quảng Ninh'),
    (48,' Quảng Trị'),
    (49,' Sóc Trăng'),
    (50,' Sơn La'),
    (51,' Tây Ninh'),
    (52,' Thái Bình'),
    (53,' Thái Nguyên'),
    (54,' Thanh Hoá'),
    (55,' Thừa Thiên Huế'),
    (56,' Tiền Giang'),
    (57,' Trà Vinh'),
    (58,' Tuyên Quang'),
    (59,' Vĩnh Long'),
    (60,' Vĩnh Phúc'),
    (61,' Yên Bái'),
)

PAYMENT_TYPE = (
    (1, "VISA/CARD"),
    (2, "CASH - COD")
)